# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: phumadie/mt_dev:rsync
# image: phumadie/mt_dev:nodejs

pipelines:
  branches:
    deployment/staging:
      - step:
          name: Staging deployment
          deployment: staging
          script:
            - cd ./wp-content/themes/theme_name/deployment && bash -e ./deploy.sh 'staging'
    deployment/production:
      - step:
          name: Production deployment
          deployment: production
          caches:
            - nodemodules
          script:
            - . ~/.nvm/nvm.sh
            - nvm use 10.12.0
            - cd ./wp-content/themes/theme_name
            - npm install
            - npm run deploy:prod

definitions:
  caches:
    nodemodules: ./wp-content/themes/theme_name/node_modules